reactor/reactor-kafka

- src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
- src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java
#31 fix overflow at `requestsPending.addAndGet` in case of `Long.MAX_VALUE + 1`
> #31 fix overflow at requestsPending.addAndGet in case of Long.MAX_VALUE + 1

- src/main/java/reactor/kafka/receiver/ReceiverOptions.java
- src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
- src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
@OlegDokuka I took a crack at implementing what's mentioned in https://github.com/reactor/reactor-kafka/issues/57
Let me know what you think
> [#57] Enable Receiver Publishing Scheduler Configuration

- src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
- src/main/java/reactor/kafka/receiver/internals/OperatorUtils.java
- src/test/java/reactor/kafka/receiver/internals/OperatorUtilsTest.java
> fix issue with incorrect value adding in case pending is negative

- README.md
- gradle.properties
- gradle/releaser.gradle
- gradle/setup.gradle
> Switch to Europium versions, -SNAPSHOT scheme

- src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
- use millis instead of nanos - Kafka converts to millis anyway
- add a comment to the for loop to explain why it's needed
- remove the unnecessary `consumer.wakeup`
@bsideup - it turns out that the loop is necessary
> CloseEvent Polishing

- src/test/java/reactor/kafka/sender/KafkaSenderTest.java
This change removes the `.multicast().onBackpressureError()` ref
since it was (temporarily) removed.
> Sync with the latest Reactor Core

- src/test/java/reactor/kafka/AbstractKafkaTest.java
Upgrade kafka container to `5.5.1` and rework deprecated API in `Testcontainers`
> upgrade kafka docker version

- src/main/java/reactor/kafka/sender/ImmutableSenderOptions.java
- src/test/java/reactor/kafka/sender/SenderOptionsTest.java
- argument passed in was ignored
> Fix ImmutableSenderOptions.closeTimeout()

- build.gradle
- src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java
- src/test/java/reactor/kafka/mock/MockProducer.java
- src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
- src/test/java/reactor/kafka/util/ConsumerDelegate.java
> Upgrade kafka clients to 2.6

- build.gradle
- src/main/java/reactor/kafka/receiver/ImmutableReceiverOptions.java
- src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
- src/main/java/reactor/kafka/sender/internals/SendSubscriber.java
- src/test/java/reactor/kafka/mock/MockConsumer.java
- src/test/java/reactor/kafka/mock/MockProducer.java
- src/test/java/reactor/kafka/util/ConsumerDelegate.java
- also suppress `NonNull` annotation messages
> Fix deprecation and other compiler warnings

- build.gradle
> Remove JCenter from build

- src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
Log current positions and committed offsets on assignment.
Tested with spring-kafka.
> Add Trace Diagnostics for Consumers

- src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
`KafkaReceiverTest.sendTransactionalReadCommitted` had a race condition;
the receiver could have received records before the assertion that was
attempting to verify all sends were done atomically.
Instead, verify that each partition has exactly one transactional marker
at the end.
> Fix Race In Test

- src/main/java/reactor/kafka/receiver/internals/AckMode.java
- src/main/java/reactor/kafka/receiver/internals/AtmostOnceOffsets.java
- src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
- src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
- src/main/java/reactor/kafka/sender/internals/DefaultKafkaOutbound.java
- src/main/java/reactor/kafka/sender/internals/DefaultTransactionManager.java
- src/main/java/reactor/kafka/sender/internals/KafkaOutboundThen.java
- src/main/java/reactor/kafka/sender/internals/Response.java
- src/main/java/reactor/kafka/sender/internals/SendSubscriber.java
- src/test/java/reactor/kafka/receiver/internals/ChaosConsumerFactory.java
- src/test/java/reactor/kafka/receiver/internals/KafkaReceiverInternalTest.java
- src/test/java/reactor/kafka/util/ConsumerDelegate.java
Follow-up to #223.
See reactor/reactor#682.
> [chores] Add or fix copyright header of files added in 1.3.x

- src/main/java/reactor/kafka/receiver/ReceiverPartition.java
- src/main/java/reactor/kafka/receiver/internals/SeekablePartition.java
- src/test/java/reactor/kafka/AbstractKafkaTest.java
- src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
Resolves https://github.com/reactor/reactor-kafka/issues/224
> GH-224: Support seekToTimestamp

- src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
- src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
> GH-233: Wake the consumer when the back pressure is relieved

- src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
> Remove info log from ConsumerEventLoop#SubscribeEvent class

- src/main/java/reactor/kafka/receiver/ImmutableReceiverOptions.java
Missing `maxDeferredCommits` field.
> Fix ImmutableReceiverOptions hashCode/Equals

- src/main/java/reactor/kafka/receiver/internals/CommittableBatch.java
Replace LinkedList with TreeSet for deferred and uncommitted offset queues to ensure acknowledgements scale at O(log n) as opposed to O(n) in respect to queue sizes when using deferred commits.
Fixes #299.
I also benchmarked 3 potential implementations to compare the performance (microseconds per scenario, lower is better) by simulating the acknowledgement and committing of 100, 1 000, 10 000 and 100 000 records in random order while using deferred commits ([benchmark code](https://gist.github.com/pdanelson/3deaa0f2d460e0ff698b94c3dda6a4ad)):
- LINKED_LIST - The existing implementation
- TREE_SET - The PR implementation
- NO_CHECK - Implementation without any checks for duplicate offsets in deferred or uncommitted queues (simply the removal of the `.contains(...)` invocations in …
> Improve ack throughput with deferred commits

- src/docs/asciidoc/api-guide.adoc
- src/docs/asciidoc/examples.adoc
> Add receiver retry section to docs

- build.gradle
- gradle/libs.versions.toml
- src/docs/asciidoc/api-guide.adoc
- src/main/java/reactor/kafka/receiver/ImmutableReceiverOptions.java
- src/main/java/reactor/kafka/receiver/MicrometerConsumerListener.java
- src/main/java/reactor/kafka/receiver/ReceiverOptions.java
- src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
- src/main/java/reactor/kafka/sender/ImmutableSenderOptions.java
- src/main/java/reactor/kafka/sender/MicrometerProducerListener.java
- src/main/java/reactor/kafka/sender/SenderOptions.java
- src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java
- src/test/java/reactor/kafka/receiver/internals/KafkaReceiverInternalTest.java
- src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java
- src/test/java/reactor/kafka/sender/KafkaSenderTest.java
Resolves https://github.com/reactor/reactor-kafka/issues/206#issuecomment-1006119883
cherry-picked Gary's commit (#5ad18b4), from [here](https://github.com/reactor/reactor-kafka/pull/262/commits), resolved conflicts, fixed copyrights and sinces. 
I did not port the changes around compatibility, since they are not necessary at the moment and we don't really know if and when micrometer v2 will go ahead.
> Add Micrometer Support for Consumer and Producer
