reactor/reactor-kafka

.gitignore
build.gradle
reactor-kafka-api/src/test/java/reactor/kafka/receiver/ReceiverTest.java

@rajinisivaram `reactor-core` and `reactor-test` 3.0.4 have been released.
This PR also takes a change in `expectNextCount` behavior in reactor-test 3.0.4 into account.

switch to reactor-core and addons 3.0.4

---

src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java

The DefaultKafkaSender passes its actual's Context for that purpose.

Adapt to core Operators hooks now requiring a Context

---

src/main/java/reactor/kafka/receiver/ReceiverOptions.java
src/main/java/reactor/kafka/receiver/internals/ConsumerFactory.java
src/main/java/reactor/kafka/sender/SenderOptions.java
src/main/java/reactor/kafka/sender/internals/ProducerFactory.java

Why:
Being able to provide already instantiated value/key de-/serializers enables many
use cases, i.e. configurable serializers.

enable to configure de-/serializer instances

---

src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java

Added `onBackpressureLatest` to skip emitted intervals during a hang

#29 fix OverflowException in Flux.interval when kafka broker is unavailable for some time

---

src/main/java/reactor/kafka/receiver/ReceiverOptions.java
src/test/java/reactor/kafka/receiver/ReceiverOptionsTest.java

This PR addresses issue described here:
https://github.com/reactor/reactor-kafka/issues/59

ReceiverOptions.toImmutable now maintains value/key deserializers

---

README.md
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/docs/asciidoc/getting-started.adoc
src/docs/asciidoc/index.asciidoc
src/docs/asciidoc/new.adoc
src/main/java/reactor/kafka/receiver/ImmutableReceiverOptions.java
src/main/java/reactor/kafka/receiver/MutableReceiverOptions.java
src/main/java/reactor/kafka/receiver/ReceiverOptions.java
src/main/java/reactor/kafka/receiver/internals/ConsumerFactory.java
src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
src/main/java/reactor/kafka/receiver/internals/KafkaSchedulers.java
src/main/java/reactor/kafka/sender/ImmutableSenderOptions.java
src/main/java/reactor/kafka/sender/MutableSenderOptions.java
src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java
src/main/java/reactor/kafka/sender/internals/ProducerFactory.java
src/test/java/reactor/kafka/AbstractKafkaTest.java
src/test/java/reactor/kafka/cluster/EmbeddedKafkaCluster.java
src/test/java/reactor/kafka/mock/MockConsumer.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
src/test/java/reactor/kafka/receiver/ReceiverOptionsTest.java
src/test/java/reactor/kafka/receiver/internals/KafkaSchedulersTest.java
src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java

* Clean-up immutability for Sender and Receiver options
* migrate to kafka 2.0.0
* update gradle to 4.10
* removed redundant KafkaScheduler#fromWorker (replaced to Schedulers.single())
* update to Reactor 3.2.0.RELEASE
* update docs to upcoming release

Maintenance update

---

src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java
src/test/java/reactor/kafka/sender/KafkaSenderTest.java

A pass at implementing what is mentioned in #72

[#72] Apply stopOnError to Producer send Exceptions

---

src/main/java/reactor/kafka/receiver/KafkaReceiver.java
src/main/java/reactor/kafka/sender/KafkaSender.java

Current implementation only creates default KafkaConsumer/KafkaProducer, thus making tracing such as zipkin impossible. Provide capability to allow user to provide a custom ConsumerFactory/ProducerFactory, thus allowing the creation of custom Consumer/Producer

pluggable producer/consumer factory

---

build.gradle
gradle/doc.gradle
gradle/setup.gradle

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://docs.oracle.com/javase/8/docs/api/ migrated to:  
https://docs.oracle.com/javase/8/docs/api/ ([https](https://docs.oracle.com/javase/8/docs/api/) result 200).
* http://github.com/reactor migrated to:  
https://github.com/reactor ([https](https://github.com/reactor) result 200).
* http://projectreactor.io/docs/core/release/api/ migrated to:  
https://projectreactor.io/docs/core/release/api/ ([https](https://projectreactor.io/docs/core/release/api/) result 200).
* …

URL Cleanup

---

README.md
build.gradle
gradle.properties

`1.1.x` has been branched out. We'll need to make sure if 3.3.0 adjustments are in order.

Switch master to 1.2.0 / Dysprosium

---

build.gradle

This includes tools and samples artifacts.
See reactor/reactor#667

Declare an Java9 JPMS Automatic-Module-Name for kafka

---

src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java

Remove the non required `{}` due to no parameters being passed and only the exception to stop it logging for example `error {}` and then stack trace.
Happy for suggestions if you want me to take this further and improve the messages.

Log cause of errors in DefaultKafkaSender

---

gradle/releaser.gradle
gradle/setup.gradle

This is a cherry-pick of commits 0561dc6 and 0e20bec
- [build] Add bumpVersionsInReadme, better Artifactory creds, buildId
- Added a bumpVersionsInReadme task that needs to be explicitly
executed with oldVersion, currentVersion and nextVersion properties
- For Artifactory, we declare an explicit credentials block using
alternate properties like artifactory_publish_xxx, that can be set via
an env var of the form ORG_GRADLE_PROJECT_artifactory_publish_xxx.
- We give the build info a meaningful name and id and ensure we don't
publish environment variables.
- [build] Fix Bamboo publications by removing onlyIf clause

[build] Backport latest changes to the build around releaser.gradle

---

src/main/java/reactor/kafka/receiver/internals/ConsumerFlux.java
src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java

This is a final step before we can encapsulate the logic inside the `Subscription`

Dispose `ConsumerFlux` on cancel/error

---

src/main/java/reactor/kafka/receiver/internals/ConsumerFlux.java
src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java
src/test/java/reactor/kafka/receiver/internals/TestableReceiver.java

Since `KafkaReceiver` needs access to the internal state and also
call methods on it, returning just `ConsumerFlux` isn't a viable
option.
This will allow us to asynchronously pre-initialize the state
and access it after receiving an instance of the handler.

Introduce `ConsumerHandler` abstraction

---

src/test/java/reactor/kafka/sender/KafkaSenderTest.java

Make `KafkaSenderTest#sendResponseEmitter` execute faster

---

build.gradle
reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleScenarios.java

The usage of `Sinks` was unnecessary given the existence of `Flux#publish()`
Should also fix #175

Use `ConnectableFlux` in `SampleScenarios`

---

src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
src/test/java/reactor/kafka/receiver/internals/KafkaReceiverInternalTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/193
Previously, `ConsumerEventLoop.stop()` ran the close event on the
current thread, if that thread is a receiver thread. However, the
current thread could be for a different receiver.
Always schedule the `CloseEvent` on the loop's scheduler, and wake
the consumer since the thread might be suspended in `poll()`.
Also fixes a race condition in another test.

GH-193: Always Run close() on the Event Thread

---

reactor-kafka-tools/src/test/resources/log4j.properties
src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/test/java/reactor/kafka/AbstractKafkaTest.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
src/test/resources/log4j.properties

`ConsumerEventLoop.PollEvent` should not resume partitions that it, itself,
has not paused.
Prior to https://github.com/reactor/reactor-kafka/commit/d908b815bf5a8be41b840a272e6766ad8754783d
pause/resume due to backpressure was protected by a boolean but it still unconditionally
resumed all partitions.
- reintroduce the boolean and only resume if we paused
- keep track of user-paused partitions and exclude them from resuming
Also fixes #190
Also fixes #198

Fix Partition Resumes

---

src/main/java/reactor/kafka/receiver/KafkaReceiver.java
src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java

This patch aims to improve memory usage with tweaking some defaults and and implementing few optimization. Key points:
- All `prefetch` parameters for `publishOn`s in `receive*` methods are set to 1 by default, and configurable via new overloadings
- ConsumerEventLoop is optimized based on discussion [here](https://github.com/reactor/reactor-kafka/issues/183) and #199
This PR will work better with #199, but can be merged separately.
fixes #183

Memory usage patch

---

.github/workflows/ci.yml
.github/workflows/publish.yml
gradle/releaser.gradle
gradle/setup.gradle

This commit changes the release process to be based on GitHub Actions.
CI is already performed on GHA, but that workflow will now only run
for pull_request trigger.
We define helper tasks and methods in the releaser.gradle file to help
interpret the version number. The trigger is pushing a commit to an
active maintenance branch.
The new workflow uses GitHub Environments to manage access to secrets,
especially in the case of milestones and releases as it introduces
signing of artifacts in these cases. It is split into 4 jobs, 3 of
which are conditional and depend on a GitHub Environment.
Notably:
- Add a function to qualify a version number as one of RELEASE,
MILESTONE, SNAPSHOT or BAD
- Add a GitHub Actions oriented task, `qualifyVersionGha`, which
produces gha step output for the current …

GitHub Actions Release Process: signing, artifactory, sonatype

---

.github/workflows/publish.yml
src/docs/asciidoc/api-guide.adoc
src/docs/asciidoc/examples.adoc
src/docs/asciidoc/getting-started.adoc

This is in preparation of renaming master to main.
Targeting 1.2.x to align documentation and build on both maintened branches.﻿

Renamed branch master to main

---

src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java
src/test/java/reactor/kafka/mock/MockProducer.java
src/test/java/reactor/kafka/sender/KafkaSenderTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/215
The `KafkaSender` has 2 schedulers, one that allows blocking (for send and close)
and one for publishing send results, which does not allow blocking.
Kafka `Producer` `initTransactions`, `commitTransaction` and `abortTransaction`
methods are blocking calls; they were incorrectly called on the second thread, as
detected by `BlockHound`. They should be called on the thread that allows blocking.
Furthermore, `beginTransaction()`, `send()`, `commitTransaction()` must be called in
sequence so `beginTransation()` is also moved to that same thread.
While testing this change, one test that uses `sink.asFlux` to publish records to
send failed. This is because the ultimate subscription to that flux is async and
was not completed before …

GH-215: Fix Blocking Calls on Sender Thread

---

src/docs/asciidoc/examples.adoc

Resolves https://github.com/reactor/reactor-kafka/issues/144
`Schedulers.newsingle()` does not allow calling `block()` on the commit `Mono`.

GH-144: Fix Doc for Manual Offset Commit

---

.github/workflows/ci.yml
src/test/java/reactor/kafka/sender/KafkaSenderTest.java

GH-215 added this test, but it is invalid because `stopOnError(false)` makes no
sense for a transactional send, since the transaction will be rolled back anyway.
If this occurs before the record is actually sent, no record is available at the
consumer (which is not transactional anyway so it can "see" uncommitted records
(which is why it worked most of the time).
Remove the test; the same PR added verification that the blocking calls were made
on the correct thread.
Also add failed test artifact upload for PR builds.

GH-215: Remove Invalid Test

---

reactor-kafka-tools/src/test/java/reactor/kafka/tools/perf/ConsumerPerformanceTest.java
reactor-kafka-tools/src/test/java/reactor/kafka/tools/perf/EndToEndLatencyTest.java
reactor-kafka-tools/src/test/java/reactor/kafka/tools/perf/ProducerPerformanceTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/230
They are time-sensitive and not suitable for CI environments.

GH-230: @Ignore Performance Tests

---

build.gradle
src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/test/java/reactor/kafka/receiver/internals/BackPressureTests.java

Resolves https://github.com/reactor/reactor-kafka/issues/237
After a rebalance, the assigned partitions do not honor the paused state.
Re-pause the partitions in the `RebalanceListener`.
- add mock test to verify `pause()` is called again
- also tested with a stand-alone Boot app

Take pause into account while rebalancing

---

build.gradle
src/main/java/reactor/kafka/receiver/ReceiverRecord.java
src/test/java/reactor/kafka/mock/MockConsumer.java
src/test/java/reactor/kafka/receiver/internals/ReceiverRecordTests.java
src/test/java/reactor/kafka/util/ConsumerDelegate.java
src/test/java/reactor/kafka/util/ConsumerDelegateTests.java

The upcoming 3.0.0 release adds a new method to `Consumer` and removes
a deprecated one from `ConsumerRecord`.
Use reflection for these two methods to enable reactor-kafka to be used
with the older clients as well as 3.0.0 when used in other projects, such
as Spring for Apache Kafka.

kafka-clients 3.0.0 Compatibility

---

build.gradle
src/docs/asciidoc/api-guide.adoc
src/main/java/reactor/kafka/receiver/ImmutableReceiverOptions.java
src/main/java/reactor/kafka/receiver/ReceiverOptions.java
src/main/java/reactor/kafka/receiver/internals/CommittableBatch.java
src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/test/java/reactor/kafka/receiver/internals/OutOfOrderCommitsTests.java
src/test/java/reactor/kafka/sender/KafkaSenderTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/243
- retain a list of uncommitted offsets per partition
- defer commits for offsets that are not at the head of the list
- when a gap is filled, commit up to the next gap
- pause consumer when `maxDeferredCommits` reached

Support Out of Order Commits

---

src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
src/main/java/reactor/kafka/sender/TransactionManager.java
src/main/java/reactor/kafka/sender/internals/DefaultTransactionManager.java
src/test/java/reactor/kafka/mock/MockConsumer.java
src/test/java/reactor/kafka/sender/internals/MockTransactionTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/207
Use `sendOffsetsToTransaction` that takes `ConsumerGroupMetadata` instead of
just he consumer `group.id`.
`kafka-clients` will currently downgrade to `ALPHA` (V1) if the broker is
earlier than 2.5.

Support Exactly Once Semantics (EOS Mode BETA V2)

---

src/main/java/reactor/kafka/receiver/internals/CommittableBatch.java
src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/test/java/reactor/kafka/receiver/internals/ConsumerEventLoopTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/259
Consumer could be permanently paused if a partition is reassigned and
duplicate records received.
- purge deferred and uncommitted offset commits when a partition is revoked
- protect against duplicate entries in both maps
Also fix a small race where `isPaused()` returns false in `onRequest()` but the
consumer is about to be paused, preventing wake up - only an issue with long
poll timeouts.

Fix Out of Order Commits After Rebalance

---

reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleConsumer.java
reactor-kafka-samples/src/main/java/reactor/kafka/samples/SampleProducer.java

SimpleDateFormat is not threadsafe, and so has been swapped out with the threadsafe DateTimeFormatter implementation instead.

Swap out SimpleDateFormat with DateTimeFormatter

---

.github/workflows/publish.yml
src/main/java/reactor/kafka/sender/TransactionManager.java
src/main/java/reactor/kafka/sender/internals/DefaultTransactionManager.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java
src/test/java/reactor/kafka/receiver/internals/CommitRetryTests.java
src/test/resources/log4j2-test.xml

See https://github.com/reactor/reactor-kafka/issues/274
This test had several problems:
The second part of the test was receiving from the original topic instead
of the destination topic so it always succeeeded in finding all the records.
When this was changed to consume from the proper topic, it always failed.
This was because the `.take(count)` in `receiveAndSendTransactions` caused
the flux to be canceled before the final commit took place.
Added a callback hook to the `TransactionManager` so we can test that the commit
is complete before terminating the flux.
It is not clear whether these fixes will resolve the original problem so I
have left diagnostics for future failure analysis.
Also capture test results in the publish action.

KafkaReceiverTest.transactionalOffsetCommit Fixes

---

src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java

If a user pauses partitions, then back pressure is applied, pausing all partitions,
the user paused partitions are not resumed when the back pressure is relieved.
However, if back pressure is in place when the user pauses partitions, they are
resumed when the back pressure is relieved.
Instead of determining user paused partitions dynamically, maintain a collection
thereof when the user invokes pause or resume on the consumer.

Fix Pause During Back Pressure

---

src/test/java/reactor/kafka/mock/MockConsumer.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java

Fix Uneventful NPE in MockConsumer

---

src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/test/java/reactor/kafka/receiver/internals/OutOfOrderCommitsTests.java

Resolves https://github.com/reactor/reactor-kafka/issues/301
Also fix race in `OutOfOrderCommitsTests.rebalance()`.

GH-301: Improve Partitions Resumed Log

---

src/main/java/reactor/kafka/receiver/internals/CommittableBatch.java
src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
src/test/java/reactor/kafka/receiver/internals/CommitRetryTests.java

Resolves https://github.com/reactor/reactor-kafka/issues/314
During cooperative rebalancing, e.g. with `CooperativeStickyAssignor` commits can result in `RebalanceInProgressException`; this exception represents a retryable condition, even though that exception does not extend the existing `RetriableCommitFailedException` or its super interface `RetriableException` so the event loop does not retry these exceptions.
Add this exception to the retryable exception list. Also, do not pause the consumer during retries because it can continue to consume from partitions that were not revoked by the cooperative rebalance.
Add unit test; integration testing was performed with the code provided in the original issue #314.

GH-314: Fix Cooperative Incremental Rebalance

---

src/main/java/reactor/kafka/sender/internals/SendSubscriber.java

Fix for #309 
Changed log level to trace. Full reasoning in the issue, but in summary: the error is thrown anyways and can/should be managed/logged by the users of the library. The logging statement in the internal file was on `error` level, which is too high and caused issues in our monitoring system.

Fix invasive logging (#309)

---

src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java

Resolves https://github.com/reactor/reactor-kafka/issues/327

GH-327: Catch WakeupException on syncCommit()

---

reactor-kafka-tools/src/main/java/reactor/kafka/tools/perf/ConsumerPerformance.java
reactor-kafka-tools/src/main/java/reactor/kafka/tools/perf/EndToEndLatency.java
reactor-kafka-tools/src/main/java/reactor/kafka/tools/perf/ProducerPerformance.java

This gets rid of some Warning: 
nothing should change except moving away from deprecated method to build arg, after the change:
```
java -cp .:reactor-kafka-tools-1.3.18-SNAPSHOT.jar:argparse4j-0.9.0.jar reactor.kafka.tools.perf.ProducerPerformance
usage: producer-performance [-h] --topic TOPIC --num-records NUM-RECORDS --record-size RECORD-SIZE --throughput THROUGHPUT --producer-props PROP-NAME=PROP-VALUE [PROP-NAME=PROP-VALUE ...] [--reactive REACTIVE] [--transactional-id TRANSACTIONAL-ID]
[--transaction-duration-ms TRANSACTION-DURATION]
This tool is used to verify the producer performance.
named arguments:
-h, --help             show this help message and exit
--topic TOPIC          produce messages to this topic
--num-records NUM-RECORDS
number of messages to produce
--record-size …
```

newArgumentParser was deprecated

---

src/main/java/reactor/kafka/sender/internals/DefaultKafkaSender.java
src/test/java/reactor/kafka/sender/internals/MockSenderTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/349
Producers are not initialized until the first send is performed.
Fence a previously defunct transacional producer as soon as possible to cancel any outstanding transaction.
Previously, consumers would be blocked until the partial transaction timed out.

GH-349: Eagerly Initialize Transactional Producers

---

src/main/java/reactor/kafka/receiver/ReceiverPartition.java
src/main/java/reactor/kafka/receiver/internals/SeekablePartition.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/344
Provide a mechanism to obtain beginning and ending offsets during partition assignment.

GH-344: ReceiverPartition Improvements

---

src/docs/asciidoc/api-guide.adoc
src/main/java/reactor/kafka/receiver/KafkaReceiver.java
src/main/java/reactor/kafka/receiver/internals/DefaultKafkaReceiver.java
src/test/java/reactor/kafka/AbstractKafkaTest.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java

This PR is an implementation to resolve #261. I have chosen the name proposed by @serejke [here](https://github.com/reactor/reactor-kafka/issues/261#issuecomment-1011481582) for the new method in KafkaReceiver.
Actually, in our product I use receive() with the bufferTimeout operator. But it is not the best solution to consume a record batch. With the receiveBatch() method batch consumption will be easier.

Add receive batch to receiver

---

src/main/java/reactor/kafka/receiver/internals/ConsumerHandler.java
src/test/java/reactor/kafka/receiver/KafkaReceiverTest.java

Resolves https://github.com/reactor/reactor-kafka/issues/333

GH-333: Support currentLag() in doOnConsumer

---

src/docs/asciidoc/api-guide.adoc
src/main/java/reactor/kafka/receiver/ImmutableReceiverOptions.java
src/main/java/reactor/kafka/receiver/ReceiverOptions.java
src/main/java/reactor/kafka/receiver/internals/ConsumerEventLoop.java
src/test/java/reactor/kafka/receiver/internals/PauseRebalanceTests.java

Resolves [#307](https://github.com/reactor/reactor-kafka/issues/307)
In order to achieve graceful shutdown during deployment, We applied the following strategy:
1. Pause old kafka consumer
2. Process in-flight messages
3. Application fully shutdown.
But when new consumers join the consumer group, after rebalance, old consumers wake up, if the newly assigned partitions are not in the pausedByUser, consumer start poll messages which gracefully shutdown are not fully achieved. 
Add pauseAllAfterRebalance configuration
When a user pauses topics/partitions before rebalancing, the behavior depends on the value of pauseAllAfterRebalance.If it is set to False, the paused topics/partitions will remain paused after the rebalance. However, if it is set to True, all assigned topics/partitions will be …

RePause All Partitions After Rebalance if user paused any and requested

---

src/docs/asciidoc/api-guide.adoc
src/docs/asciidoc/examples.adoc

It seems example code is broken.

Fix broken example code ('retry(When' -> 'retryWhen')

---

src/main/java/reactor/kafka/receiver/ReceiverOptions.java
src/main/java/reactor/kafka/sender/SenderOptions.java
src/test/java/reactor/kafka/receiver/ReceiverOptionsTest.java
src/test/java/reactor/kafka/sender/SenderOptionsTest.java

Resolves #374
Introduces support for reading the boot servers when the property was defined as a List and not a String.
It will avoid a class cast exception when using reactor-kafka with Spring Boot Kafka since the Spring library configures the bootstrap servers as a list of strings and not a String object, as you can see on [their implementation](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#L71).

support to read bootstrap server property when it was defined as a list

---

src/test/java/reactor/kafka/receiver/internals/MockReceiverTest.java

This test fails consistently with reactor-core 3.7.0-SNAPSHOT

Ignore temporarily MockReceiverTest#consumerMethods

---

.github/dependabot.yml

Fixes: #395
Issue link: https://github.com/reactor/reactor-kafka/issues/395
* Added `dependabot.yml` config for both `main` and `1.3.x` supported branches
* Include updates of `package-ecosystem` for Gradle and GitHub Actions
* Extract `development-dependencies` group for those dependencies which are used only for this project development: all the test dependencies, `compileOnly` and Gradle plugins
Note: had to rename label in project repository to the `type: dependency-upgrade` and also added `type: task`

GH-395: Add Dependabot support to the project

---

.github/dependabot.yml

* Kafka and Micrometer deps as `type/dependency-upgrade`
* All other as `type/chores`

Regroup Dependabot updates
